<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Data_Engineering_SWEN739')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('description', '')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('images/favicon.ico')])
//             ->appendStylesheet($this->basePath('adm/css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-arabic.min.css'))
            ->appendStylesheet($this->basePath('adm/css/admin.css'))
            ->appendStylesheet($this->basePath('adm/css/admin-rtl.css'))
            ->appendStylesheet($this->basePath('adm/font-awesome/css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('adm/chosen_v1.8.5/chosen.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('adm/js/jquery.js'))
//             ->appendFile($this->basePath('adm/js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/bootstrap-arabic.min.js'))
            ->appendFile($this->basePath('adm/js/tinymce/tinymce.min.js'))
            ->appendFile($this->basePath('adm/chosen_v1.8.5/chosen.jquery.min.js'))
            ->appendFile($this->basePath('adm/js/adm.global.js'))
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">
        body { margin-top: 0px; }
        </style>
    </head>
	<body>
		<?php echo $this->content; ?>
	</body>
</html>
