<?php
echo $this->doctype(); ?>
<html lang="ar<?php //echo \Locale::getDefault(); ?>" class="no-js">
    <head>
	   <meta charset="utf-8">
       <?php echo $this->headTitle('BMS '. $this->translate('Home'))->setSeparator(' - ')->setAutoEscape(false) ?>
	   <meta name="viewport" content="width=device-width, initial-scale=1">
       
       <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'images/ficon.ico'))
        				->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700')
                        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/studentsFollowup/css/reset.css')
                        ->appendStylesheet($this->basePath() . '/studentsFollowup/css/style.css')
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()//->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->appendFile($this->basePath() . '/studentsFollowup/js/modernizr.js')
                                      ->appendFile($this->basePath() . '/studentsFollowup/js/jquery-2.1.1.js')
                                      ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
                                      ->appendFile($this->basePath() . '/studentsFollowup/js/jquery.mixitup.min.js')
                                      ->appendFile($this->basePath() . '/studentsFollowup/js/velocity.min.js')
                                      ->appendFile($this->basePath() . '/studentsFollowup/js/main.js')
        ?>
</head>
<body>
    <?php echo $this->content; ?>
</body>
</html>