<?php
if (isset($form)) {
    echo $this->bundleForm($form);
}?>

<script>
    function add_new_fieldset() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        
        $('form > fieldset').append(template);

        tinymceInit();
        
        return false;
    }

    $(document).on('click', '.remove-this-fieldset', function() {
        $(this).parent().parent().parent().remove();
    });
</script>
<style>
fieldset {
    border: 1px groove #ddd !important;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    -webkit-box-shadow:  0px 0px 0px 0px #000;
    box-shadow:  0px 0px 0px 0px #000;
    background-color: #f7f7f7;
}

legend {
    width:auto;
    padding:0 10px;
    border-bottom:none;
}
</style>
